apiVersion: apps/v1
kind: Deployment
metadata:
  name: album-api-deployment
  labels:
    app: album-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: album-api
  template:
    metadata:
      labels:
        app: album-api
    spec:
      containers:
      - name: album-api
        image: blessmwafu/album-api:1.0.19
        ports:
        - containerPort: 8080